name: noise
channels:
    - default
    - conda-forge
dependencies:
    - python>=3.8
    - nomkl
    - numpy
    - matplotlib
    - pandas
    - pytest
    - pytest-cov
    - scikit-image
    - scikit-learn
    - scipy
    - dask
    - distributed
    - dask-jobqueue
    - jupyterlab
    - numba
    - nodejs
    - pip
    - pip:
      - joblib
      - jupyter-server-proxy
      - dask_labextension
      - hypothesis
