name: noise
channels:
    - default
    - conda-forge
dependencies:
    - python=3.8
    - nomkl=1.0
    - numpy=1.19.2
    - pandas=1.1.3
    - pytest=6.1.1
    - pytest-cov=2.10.1
    - scikit-image=0.17.2
    - scikit-learn=0.23.2
    - scipy=1.5.2
    - dask=2.30.0
    - distributed=2.30.0
    - dask-jobqueue=0.7.1
    - jupyterlab=1.1.3
    - numba=0.51.2
    - nodejs=10.13.0
    - pip=20.2.4
    - pip:
      - joblib==0.17.0
      - autograd==1.3
      - jupyter-server-proxy==1.5.0
      - dask_labextension==3.0.0
